### ISSUE TITLE
Increase and Decrease Counter show up for all extracts

### ISSUE THREAD

**Issue by haveric** [Jehree/InteractableExfilsAPI#1]
​Just a heads up that there's now an "Increase Counter" and "Decrease Counter" that shows up for extracts below the extract command, which I don't think is meant to be there by default​. I initially saw just the counters at Scav House on woods as a PMC, which was a little confusing.
![image](https://github.com/user-attachments/assets/d8d8f839-c025-48cc-b484-9959f4d4007b)

**Comment by Jehree** [comment]
Haha sorry about that, should be fixed
